[
  {
    cat_id:1,
    name:'Google Pixel 6a',
    location:'Mirpur',
    resale_price:200,
    original_price:300,
    years_used:1,
    posting_time:'20 January 2023',
    seller_name: 'Alan Walker',
    verified: true,
    img:'https://i.ibb.co/sttcTrh/budget-phone1.webp',
    status:'available',
    advertise:false,
    reported:false,
  },{
    cat_id:1,
    name:'Samsung Galazy A53',
    location:'Mohakhali',
    resale_price:200,
    original_price:350,
    years_used:1.5,
    posting_time:'10 January 2023',
    seller_name: 'Alan Turing',
    verified: false,
    img:'https://i.ibb.co/t21HqY4/budget-phone2.webp',
    status:'available',
    advertise:false,
    reported:false,
  },{
    cat_id:2,
    name:'Poco X4 Pro 5G',
    location:'Uttara',
    resale_price:300,
    original_price:450,
    years_used:1,
    posting_time:'20 January 2022',
    seller_name: 'Alan Joe',
    verified: true,
    img:'https://i.ibb.co/jWDM1rW/midrange-phone1.jpg',
    status:'available',
    advertise:false,
    reported:false,
  },{
    cat_id:2,
    name:' Realme GT 2',
    location:'Jatrabari',
    resale_price:300,
    original_price:400,
    years_used:2,
    posting_time:'15 January 2023',
    seller_name: 'Tom Holand',
    verified: true,
    img:'https://i.ibb.co/BNnRwF6/midrange-phone2.jpg',
    status:'available',
    advertise:false,
    reported:false,
  },{
    cat_id:3,
    name:'Apple iPhone 14 Pro',
    location:'Bashundhara',
    resale_price:800,
    original_price:1200,
    years_used:.5,
    posting_time:'12 January 2023',
    seller_name: 'Tom Cruise',
    verified: true,
    img:'https://i.ibb.co/J3p1Dv1/flagship-phone1.webp',
    status:'available',
    advertise:false,
    reported:false,
  },{
    cat_id:3,
    name:'Samsung Galaxy S22 Ultra',
    location:'Bashundara',
    resale_price:700,
    original_price:1000,
    years_used:1,
    posting_time:'15 January 2023',
    seller_name: 'Micheal Phelps',
    verified: true,
    img:'https://i.ibb.co/1nXbdQh/flagship-phone2.webp',
    status:'available',
    advertise:false,
    reported:false,
  },

]